name: scry pipeline

on:
  push:
    branches: master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check style
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets -- -D clippy::all

      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo build --release
